services:
  oauth-client:
    pull_policy: always
    image: dipdeepcode/oauth-client:latest
    container_name: oauth-client
    restart: unless-stopped
    environment:
      - ISSUER_URI=${ISSUER_URI}
    ports:
      - ${APP_PORT}:8080
    networks:
      - iam-tool_net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  iam-tool_net:
    external: true
