services:
  oauth-client:
    image: dipdeepcode/oauth-client:latest
    container_name: oauth-client
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - iam-tool_net

networks:
  iam-tool_net:
    external: true