services:
  oauth-client:
    image: dipdeepcode/oauth-client:latest
    container_name: oauth-client
    restart: unless-stopped
    environment:
      - ISSUER_URI=${ISSUER_URI}
    ports:
      - ${APP_PORT}:8080
    networks:
      - iam-tool_net

networks:
  iam-tool_net:
    external: true