server:
  forward-headers-strategy: native
spring:
  application:
    name: oauth-client
  profiles:
    active: develop
  security:
    oauth2:
      client:
        registration:
          iam-tool:
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: ${OAUTH_CLIENT_ID}
            client-name: ${OAUTH_CLIENT_NAME}
            client-secret: ${OAUTH_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            redirect-uri: {baseUrl}/login/oauth2/code/{registrationId}
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: ${IAM_TOOL_HOSTNAME}/realms/${IAM_REALM_NAME}
