spring:
  application:
    name: oauth-client
  security:
    oauth2:
      client:
        registration:
          iam-tool:
            client-id: ${CLIENT_ID}
#            client-name: ${OAUTH_CLIENT_NAME}
#            client-secret: ${OAUTH_CLIENT_SECRET}
            provider: keycloak
#            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}"
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
