name: Deploy oauth-client to the development stand
on: workflow_dispatch
permissions: {}
jobs:
  checkstyle:
    environment: develop
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make maven wrapper executable
        run: chmod +x mvnw
      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: "${{ runner.os }}-m2-checksytle-${{ hashFiles('**/pom.xml') }}"
      - name: Run Checkstyle
        run: ./mvnw checkstyle:check
  test:
    environment: develop
    permissions:
      contents: read
    runs-on: ubuntu-22.04
#    services:
#      keycloak:
#        image: keycloak/keycloak:26.1
#        env:
#          KC_HTTP_PORT: 8080
#          KC_HTTP_ENABLED: true
#          KC_BOOTSTRAP_ADMIN_USERNAME: admin
#          KC_BOOTSTRAP_ADMIN_PASSWORD: pass
#        ports:
#          - "8090:8080"
#        volumes:
#          - "/workspace/src/main/resources/keycloak:/src/main/resources/keycloak/"
#        options: |
#          --name keycloak
#          --
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: List repository content
        run: ls -la -r
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - name: Make maven wrapper executable
#        run: chmod +x mvnw
#      - name: Cache maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: "${{ runner.os }}-m2-test-${{ hashFiles('**/pom.xml') }}"
#      - name: Setup Keycloak realm
#        run: |
#          docker exec -it keycloak sh -c
#          "/opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password admin &&
#          /opt/jboss/keycloak/bin/kcadm.sh create realms -s realm=testrealm -s enabled=true &&
#          /opt/jboss/keycloak/bin/kcadm.sh create partialImport -r testrealm -s ifResourceExists=SKIP -o -f /src/main/resources/keycloak/realm.json"
#      - name: Run test
#        run: ./mvnw -B test --file pom.xml



#  build_and_push_iam-tool_image:
#    environment: develop
#    permissions:
#      contents: read
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ vars.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Build and push image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: 'dipdeepcode/oauth-client:latest'
